name: ee-bot

on:
  schedule:
    # KST 07–23시, 매 시 정각 (UTC 0–14,22–23)
    - cron: "0 0-14,22-23 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_EE: ${{ secrets.DISCORD_WEBHOOK_EE }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: pip install requests beautifulsoup4

      - name: Run ee_bot
        run: python ee_bot.py

      - name: Commit last_ee_id if changed
        run: |
          git config --global user.name  "ee-bot"
          git config --global user.email "bot@users.noreply.github.com"
          git diff --quiet last_ee_id.txt || \
          (git add last_ee_id.txt && git commit -m "update ee notice id" && git push)
