name: kma-weather-bot
on:
  schedule:
    # 매일 06:40 KST = UTC 21:40
    - cron: "40 21 * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      KMA_API_KEY:             ${{ secrets.KMA_API_KEY }}
      DISCORD_WEBHOOK_UMBRELLA: ${{ secrets.DISCORD_WEBHOOK_UMBRELLA }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.x" }
      - run: pip install requests
      - run: python kma_weather_bot.py
