name: mse-bot

on:
  schedule:
    - cron: '0 0-14,22-23 * * *'     # KST 07~23시, 매 시
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_MSE: ${{ secrets.DISCORD_WEBHOOK_MSE }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: pip install requests beautifulsoup4

      - name: Run materials_bot
        run: python materials_bot.py

      # ↓↓↓ 디버그 HTML 업로드 — 실행 결과에서 다운로드 가능
      - name: Upload debug html
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mse-debug
          path: mse_debug.html
          retention-days: 3

      - name: Commit last_mse_id if changed
        run: |
          git config --global user.name  "mse-bot"
          git config --global user.email "bot@users.noreply.github.com"
          git diff --quiet last_mse_id.txt || \
          (git add last_mse_id.txt && git commit -m "update mse notice id" && git push)
