name: mse-bot

on:
  schedule:
    # KST 07~23시, 매 시 정각 (UTC 0–14,22–23)
    - cron: "0 0-14,22-23 * * *"
  workflow_dispatch: {}

permissions:
  contents: write           # last_mse_id.txt 자동 커밋용

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_MSE: ${{ secrets.DISCORD_WEBHOOK_MSE }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: pip install requests beautifulsoup4

      - name: Run materials_bot
        run: python materials_bot.py

      - name: Commit last_mse_id if changed
        run: |
          git config --global user.name  "mse-bot"
          git config --global user.email "bot@users.noreply.github.com"
          git diff --quiet last_mse_id.txt || \
          (git add last_mse_id.txt && git commit -m "update mse notice id" && git push)
