name: notice-bot

on:
  schedule:
    # 매 시 정각, UTC 0~14 & 22~23 → KST 07~23
    - cron: "0 0-14,22-23 * * *"
  workflow_dispatch: {}


# ── ① GITHUB_TOKEN에 쓰기 권한 부여 ── ⬅️ 추가
permissions:
  contents: write         # 필수! push 하려면 write 권한이 있어야 함

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: pip install requests beautifulsoup4 openai feedparser

      - name: Run bot
        run: python notice_bot.py

      # ── ② PAT 대신 GITHUB_TOKEN 사용 ── ⬅️ GH_PAT 관련 줄 삭제
      - name: Commit last_notice_id if changed
        run: |
          git config --global user.name  "notice-bot"
          git config --global user.email "bot@users.noreply.github.com"
          if git diff --quiet last_notice_id.txt; then
            echo "no update"
          else
            git add last_notice_id.txt
            git commit -m "update notice id"
            git push          # 토큰 자동 주입
          fi
