name: notice-bot

on:
  schedule:
    # 30분 간격, KST 07:00 – 22:30 (UTC 22:00 – 13:30)
    - cron: "0,30 22-23,0-13 * * *"
  workflow_dispatch: {}

permissions:
  contents: write          # last_notice_id.txt 커밋용

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      OPENAI_API_KEY:      ${{ secrets.OPENAI_API_KEY }} 

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: "3.x" }

      - name: Install deps
        run: pip install requests beautifulsoup4 openai

      - name: Run notice_bot
        run: python notice_bot.py

      - name: Commit last_notice_id if changed
        run: |
          git config --global user.name  "notice-bot"
          git config --global user.email "bot@users.noreply.github.com"
          git diff --quiet last_notice_id.txt || \
          (git add last_notice_id.txt && git commit -m "update notice id" && git push)
