name: sw-bot

on:
  schedule:
    # UTC 0-14, 22-23 → KST 07-23시 매 시 정각
    - cron: "0 0-14,22-23 * * *"
  workflow_dispatch: {}

permissions:
  contents: write         # last_sw_id.txt 자동 커밋용

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_SW: ${{ secrets.DISCORD_WEBHOOK_SW }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: pip install requests beautifulsoup4

      - name: Run sw_bot
        run: python sw_bot.py

      - name: Commit last_sw_id if changed
        run: |
          git config --global user.name  "sw-bot"
          git config --global user.email "bot@users.noreply.github.com"
          if git diff --quiet last_sw_id.txt; then
            echo "no update"
          else
            git add last_sw_id.txt
            git commit -m "update sw notice id"
            git push
          fi
